services:
  - type: web
    name: e-commerce-backend
    env: node
    buildCommand: cd e-commerce-backend && npm install
    startCommand: cd e-commerce-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 